### ISSUE TITLE
Be runtime configurable

### ISSUE THREAD

**Issue by damianh** [damianh/SiteMappingMiddleware#3]
Be able to configure the site mappings dynamically without rebuilding the owin pipeline or restarting the host.

**Comment by lehne** [comment]
Did you get this working? I am trying to make a multi-tenant app that requires configuring subdomains differently per tenant dynamically and this would be perfect for it.

**Comment by damianh** [comment]
I didn't and I don't think I will. I think a better approach is to use wrapper middleware, [such as this](https://github.com/damianh/DynamicKatanaPipeline), to reconfigure _this_ middleware.

I'm using this wrapper MW to reconfigure ThinkTecture's Identity Server to support runtime re-config of ws-fed middleware. See https://github.com/IdentityServer/IdentityServer3/issues/1439#issuecomment-127511093
